UISMRCCOMP-1: Move common components from ui-quick-marc.
folio-org/stripes-marc-components pull request #4
Opened 2023-10-24 13:14 UTC by Dmytro-Melnyshyn

## Purpose
Move common components from ui-quick-marc.

## Issue

## Approach

#### TODOS and Open Questions

## Learning

## Screenshots

2023-10-25 15:03 UTC, BogdanDenis approved these changes
Looks good!

2023-10-25 15:11 UTC, BogdanDenis requested changes

2023-10-25 15:11 UTC, BogdanDenis commented on lib/MarcView/MarcContent/MarcContent.js
> +export default MarcContent;
Let's use named exports in this modules to make sure we don't rename components when importing

2023-10-30 15:26 UTC, Dmytro-Melnyshyn commented on lib/MarcView/MarcContent/MarcContent.js
> +export default MarcContent;
Thanks, fixed.

2023-10-31 09:19 UTC, BogdanDenis commented on package.json
> -    "regenerator-runtime": "^0.13.3"
I think we still need this to transpile async functions

2023-10-31 13:03 UTC, BogdanDenis approved these changes

2023-10-31 13:46 UTC, merged